## Last Working Commit with old version of AUTH system handled by host
app:
  name: "Zoneweaver"
  version: "0.0.1"
  frontend_url: "https://hv-04.home.m4kr.net"

# Mail configuration for sending invitations and notifications
mail:
  smtp_connect:
    host: "smtp.gmail.com"  # Replace with your SMTP server
    port: 587
    secure: false  # true for 465, false for other ports
  smtp_auth:
    user: "your-email@gmail.com"  # Replace with your email
    password: "your-app-password"  # Replace with your app password
  smtp_settings:
    from: "Zoneweaver <noreply@yourdomain.com>"  # Replace with your from address

server:
  hostname: "hv-04.home.m4kr.net"
  port: 3001
  ssl:
    enabled: true
    generate_ssl: true  # Only applies if existing keys do not exist
    # Set paths to your SSL certificate files
    key: "./certs/private-key.pem"
    cert: "./certs/certificate.pem"
    # Optional: CA certificate for self-signed certificates
    # ca: "./certs/ca-certificate.pem"

frontend:
  port: 443
  autoRefreshInterval: 5
  enableNotifications: true
  enableDarkMode: true

cors:
  whitelist:
    - "https://hv-04-backend.home.m4kr.net:5001"
    - "https://hv-04.home.m4kr.net:3001"
    - "https://hv-04.home.m4kr.net"
  options:
    origin: true
    preflightContinue: true
    credentials: true

backend_servers:
  - hostname: "hv-04-zapi.home.m4kr.net"
    port: 5001
    protocol: "https"
    allow_insecure: false

# Environment-specific settings
environment:
  trust_proxy: 1

# Additional settings can be added here as needed
logging:
  level: "info"
  enabled: true

limits:
  maxServersPerUser: 10

security:
  jwt_secret: "${JWT_SECRET}"
  bcrypt_rounds: 10
  sessionTimeout: 24
  allow_new_organizations: true

database:
  path: "./data/zoneweaver.db"

gravatar:
  apiKey: "4503:gk-kSPgIiM6imj2DOVlD3XV5uiXyXiF3klzQY5FQ2V3bDBohluexKlX2CR9OAPt_"
