# Zoneweaver Production Configuration - Updated to Metadata Format
# Fixed: Consolidated all frontend settings under "Frontend" section to eliminate duplicate tabs

frontend:
  name:
    type: string
    value: "ZoneWeaver"
    description: "Application display name"
    section: "Frontend"
    order: 1
  version:
    type: string
    value: "0.0.10"
    description: "Current application version"
    section: "Frontend"
    order: 2
  frontend_url:
    type: string
    value: "https://hv-04.home.m4kr.net"
    description: "Frontend URL for redirects and API responses"
    section: "Frontend"
    order: 3
  port:
    type: integer
    value: 443
    description: "Frontend port number"
    section: "Frontend"
    required: true
    validation:
      min: 1
      max: 65535
    order: 4
  auto_refresh_interval:
    type: integer
    value: 5
    description: "Auto refresh interval in seconds"
    section: "Frontend"
    validation:
      min: 1
      max: 300
    order: 5
  enable_notifications:
    type: boolean
    value: true
    description: "Enable browser notifications"
    section: "Frontend"
    order: 6
  enable_dark_mode:
    type: boolean
    value: true
    description: "Enable dark mode by default"
    section: "Frontend"
    order: 7

# Mail configuration for sending invitations and notifications
mail:
  smtp_host:
    type: host
    value: "mail-01.m4kr.net"
    description: "SMTP server hostname"
    section: "Mail"
    required: true
    order: 1
  smtp_port:
    type: integer
    value: 465
    description: "SMTP server port (587 for TLS, 465 for SSL)"
    section: "Mail"
    required: true
    validation:
      min: 1
      max: 65535
    order: 2
  smtp_secure:
    type: boolean
    value: true
    description: "Use SSL/TLS for SMTP connection"
    section: "Mail"
    order: 3
  smtp_user:
    type: email
    value: "mark.gilbert@m4kr.net"
    description: "SMTP authentication username"
    section: "Mail"
    required: true
    order: 4
  smtp_password:
    type: password
    value: "6gdZ#mTtJX9Mon5^GgR"
    description: "SMTP authentication password"
    section: "Mail"
    required: true
    order: 5
  from_address:
    type: email
    value: "ZoneWeaver <zoneweaver@m4kr.net>"
    description: "Default sender email address"
    section: "Mail"
    required: true
    order: 6

server:
  hostname:
    type: host
    value: "hv-04.home.m4kr.net"
    description: "Server hostname for external access"
    section: "Server"
    required: true
    order: 1
  port:
    type: integer
    value: 3001
    description: "Server port number"
    section: "Server"
    required: true
    validation:
      min: 1
      max: 65535
    order: 2
  ssl_enabled:
    type: boolean
    value: true
    description: "Enable HTTPS/SSL connections"
    section: "Server"
    order: 3
  ssl_generate:
    type: boolean
    value: true
    description: "Automatically generate SSL certificates if they don't exist"
    section: "Server"
    conditional:
      field: "server.ssl_enabled"
      value: true
    order: 4
  ssl_key_path:
    type: string
    value: "/etc/zoneweaver/ssl/private-key.pem"
    description: "Path to SSL private key file"
    section: "Server"
    conditional:
      field: "server.ssl_enabled"
      value: true
    order: 5
  ssl_cert_path:
    type: string
    value: "/etc/zoneweaver/ssl/certificate.pem"
    description: "Path to SSL certificate file"
    section: "Server"
    conditional:
      field: "server.ssl_enabled"
      value: true
    order: 6
  ssl_ca_path:
    type: string
    value: ""
    description: "Path to SSL CA certificate file (optional)"
    section: "Server"
    conditional:
      field: "server.ssl_enabled"
      value: true
    order: 7


cors:
  whitelist:
    type: array
    value:
      - "https://hv-04-backend.home.m4kr.net:5001"
      - "https://hv-04.home.m4kr.net:3001"
      - "https://hv-04.home.m4kr.net"
    description: "Allowed CORS origins (one per line)"
    section: "Security"
    order: 1
  options:
    origin:
      type: boolean
      value: true
      description: "Allow all origins if whitelist is empty"
      section: "Security"
      order: 2
    preflightContinue:
      type: boolean
      value: true
      description: "Pass preflight response to next handler"
      section: "Security"
      order: 3
    credentials:
      type: boolean
      value: true
      description: "Allow credentials in CORS requests"
      section: "Security"
      order: 4

# Backend servers configuration (kept as-is for compatibility)
backend_servers:
  - hostname: "hv-04-webhyve.home.m4kr.net"
    port: 5001
    protocol: "https"
    allow_insecure: false

environment:
  trust_proxy:
    type: integer
    value: 1
    description: "Trust proxy level for Express.js"
    section: "Environment"
    validation:
      min: 0
      max: 10
    order: 1

logging:
  level:
    type: select
    value: "info"
    description: "Logging level"
    section: "Logging"
    options:
      - { value: "error", label: "Error" }
      - { value: "warn", label: "Warning" }
      - { value: "info", label: "Info" }
      - { value: "debug", label: "Debug" }
    order: 1
  enabled:
    type: boolean
    value: true
    description: "Enable logging"
    section: "Logging"
    order: 2

limits:
  max_servers_per_user:
    type: integer
    value: 10
    description: "Maximum servers per user"
    section: "Performance"
    validation:
      min: 1
      max: 100
    order: 1

  # Rate Limiting Configuration (moved from rateLimiting section)
  authentication:
    windowMs:
      type: integer
      value: 900000
      description: "Authentication rate limit window in milliseconds (15 minutes)"
      section: "Performance"
      required: true
      order: 2
    max:
      type: integer
      value: 25
      description: "Maximum authentication attempts per window"
      section: "Performance"
      required: true
      validation:
        min: 1
        max: 1000
      order: 3
    message:
      type: string
      value: "Too many authentication attempts, please try again later"
      description: "Error message for authentication rate limit"
      section: "Performance"
      required: true
      order: 4

  admin:
    windowMs:
      type: integer
      value: 900000
      description: "Admin operations rate limit window in milliseconds (15 minutes)"
      section: "Performance"
      required: true
      order: 5
    max:
      type: integer
      value: 500
      description: "Maximum admin requests per window"
      section: "Performance"
      required: true
      validation:
        min: 1
        max: 10000
      order: 6
    message:
      type: string
      value: "Too many admin requests, please try again later"
      description: "Error message for admin rate limit"
      section: "Performance"
      required: true
      order: 7

  apiProxy:
    windowMs:
      type: integer
      value: 60000
      description: "API proxy rate limit window in milliseconds (1 minute)"
      section: "Performance"
      required: true
      order: 8
    max:
      type: integer
      value: 100
      description: "Maximum API proxy requests per window"
      section: "Performance"
      required: true
      validation:
        min: 1
        max: 10000
      order: 9
    message:
      type: string
      value: "Too many API proxy requests, please try again later"
      description: "Error message for API proxy rate limit"
      section: "Performance"
      required: true
      order: 10

  realtime:
    windowMs:
      type: integer
      value: 60000
      description: "Real-time operations rate limit window in milliseconds (1 minute)"
      section: "Performance"
      required: true
      order: 11
    max:
      type: integer
      value: 250
      description: "Maximum real-time requests per window"
      section: "Performance"
      required: true
      validation:
        min: 1
        max: 10000
      order: 12
    message:
      type: string
      value: "Too many real-time requests, please try again later"
      description: "Error message for real-time rate limit"
      section: "Performance"
      required: true
      order: 13

  standard:
    windowMs:
      type: integer
      value: 900000
      description: "Standard operations rate limit window in milliseconds (15 minutes)"
      section: "Performance"
      required: true
      order: 14
    max:
      type: integer
      value: 1000
      description: "Maximum standard requests per window"
      section: "Performance"
      required: true
      validation:
        min: 1
        max: 100000
      order: 15
    message:
      type: string
      value: "Too many requests, please try again later"
      description: "Error message for standard rate limit"
      section: "Performance"
      required: true
      order: 16

  staticFiles:
    windowMs:
      type: integer
      value: 900000
      description: "Static file serving rate limit window in milliseconds (15 minutes)"
      section: "Performance"
      required: true
      order: 17
    max:
      type: integer
      value: 5000
      description: "Maximum static file requests per window"
      section: "Performance"
      required: true
      validation:
        min: 1
        max: 100000
      order: 18
    message:
      type: string
      value: "Too many static file requests, please try again later"
      description: "Error message for static file rate limit"
      section: "Performance"
      required: true
      order: 19

# Authentication Configuration
authentication:
  enabled_strategies:
    type: array
    value: ["local", "jwt"]
    description: "Enabled authentication strategies"
    section: "Authentication"
    order: 1
  default_strategy:
    type: select
    value: "local"
    description: "Default authentication strategy"
    section: "Authentication"
    options:
      - { value: "local", label: "Local" }
      - { value: "jwt", label: "JWT" }
      - { value: "ldap", label: "LDAP" }
    order: 2

  # JWT settings
  jwt_secret:
    type: password
    value: "${JWT_SECRET}"
    description: "JWT signing secret"
    section: "Authentication"
    required: true
    order: 3
  jwt_expiration:
    type: string
    value: "24h"
    description: "JWT token expiration time"
    section: "Authentication"
    order: 4
  jwt_issuer:
    type: string
    value: "zoneweaver"
    description: "JWT token issuer"
    section: "Authentication"
    order: 5
  jwt_audience:
    type: string
    value: "zoneweaver-api"
    description: "JWT token audience"
    section: "Authentication"
    order: 6

  # Local authentication settings
  local_enabled:
    type: boolean
    value: true
    description: "Enable local username/password authentication"
    section: "Authentication"
    order: 7
  local_require_email_verification:
    type: boolean
    value: false
    description: "Require email verification for local accounts"
    section: "Authentication"
    order: 8
  local_password_min_length:
    type: integer
    value: 8
    description: "Minimum password length"
    section: "Authentication"
    validation:
      min: 4
      max: 50
    order: 9
  local_password_require_uppercase:
    type: boolean
    value: false
    description: "Require uppercase letters in passwords"
    section: "Authentication"
    order: 10
  local_password_require_lowercase:
    type: boolean
    value: false
    description: "Require lowercase letters in passwords"
    section: "Authentication"
    order: 11
  local_password_require_numbers:
    type: boolean
    value: false
    description: "Require numbers in passwords"
    section: "Authentication"
    order: 12
  local_password_require_symbols:
    type: boolean
    value: false
    description: "Require symbols in passwords"
    section: "Authentication"
    order: 13
  local_bcrypt_rounds:
    type: integer
    value: 10
    description: "BCrypt hashing rounds"
    section: "Authentication"
    validation:
      min: 4
      max: 20
    order: 14
  local_session_timeout:
    type: integer
    value: 24
    description: "Session timeout in hours"
    section: "Authentication"
    validation:
      min: 1
      max: 168
    order: 15
  local_allow_new_organizations:
    type: boolean
    value: true
    description: "Allow users to create new organizations"
    section: "Authentication"
    order: 16

  # LDAP settings (currently disabled)
  ldap_enabled:
    type: boolean
    value: false
    description: "Enable LDAP authentication"
    section: "Authentication"
    order: 17
  ldap_url:
    type: string
    value: ""
    description: "LDAP server URL"
    section: "Authentication"
    placeholder: "ldap://localhost:389"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 18
  ldap_bind_dn:
    type: string
    value: ""
    description: "LDAP bind DN"
    section: "Authentication"
    placeholder: "cn=admin,dc=example,dc=com"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 19
  ldap_bind_credentials:
    type: password
    value: ""
    description: "LDAP bind credentials"
    section: "Authentication"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 20
  ldap_search_base:
    type: string
    value: ""
    description: "LDAP search base"
    section: "Authentication"
    placeholder: "ou=users,dc=example,dc=com"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 21
  ldap_search_filter:
    type: string
    value: ""
    description: "LDAP search filter"
    section: "Authentication"
    placeholder: "(uid={{username}})"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 22
  ldap_search_attributes:
    type: string
    value: ""
    description: "LDAP search attributes (comma separated)"
    section: "Authentication"
    placeholder: "displayName,mail,memberOf"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 23
  ldap_tls_reject_unauthorized:
    type: boolean
    value: false
    description: "Reject unauthorized TLS certificates"
    section: "Authentication"
    conditional:
      field: "authentication.ldap_enabled"
      value: true
    order: 24

  # External provider settings
  external_domain_mapping_enabled:
    type: boolean
    value: false
    description: "Enable domain-to-organization mapping"
    section: "Authentication"
    order: 25
  external_domain_mappings:
    type: textarea
    value: ""
    description: "Domain mappings (JSON format)"
    section: "Authentication"
    conditional:
      field: "authentication.external_domain_mapping_enabled"
      value: true
    order: 26
  external_provisioning_enabled:
    type: boolean
    value: false
    description: "Enable automatic user provisioning"
    section: "Authentication"
    order: 27
  external_provisioning_policy:
    type: select
    value: "invite_only"
    description: "External user provisioning policy"
    section: "Authentication"
    options:
      - { value: "invite_only", label: "Invite Only" }
      - { value: "auto_provision", label: "Auto Provision" }
      - { value: "manual_approval", label: "Manual Approval" }
      - { value: "disabled", label: "Disabled" }
    conditional:
      field: "authentication.external_provisioning_enabled"
      value: true
    order: 28
  external_provisioning_default_role:
    type: select
    value: "user"
    description: "Default role for provisioned users"
    section: "Authentication"
    options:
      - { value: "user", label: "User" }
      - { value: "admin", label: "Admin" }
    conditional:
      field: "authentication.external_provisioning_enabled"
      value: true
    order: 29
  external_provisioning_fallback_action:
    type: select
    value: "require_invite"
    description: "Action when provisioning fails"
    section: "Authentication"
    options:
      - { value: "require_invite", label: "Require Invite" }
      - { value: "create_org", label: "Create Organization" }
      - { value: "deny_access", label: "Deny Access" }
    conditional:
      field: "authentication.external_provisioning_enabled"
      value: true
    order: 30
  external_profile_sync_enabled:
    type: boolean
    value: true
    description: "Enable profile synchronization"
    section: "Authentication"
    order: 31
  external_profile_update_on_login:
    type: boolean
    value: true
    description: "Update profile on each login"
    section: "Authentication"
    conditional:
      field: "authentication.external_profile_sync_enabled"
      value: true
    order: 32
  external_profile_sync_fields:
    type: string
    value: "displayName,email,groups"
    description: "Profile fields to sync (comma separated)"
    section: "Authentication"
    conditional:
      field: "authentication.external_profile_sync_enabled"
      value: true
    order: 33

# Database configuration
database:
  dialect:
    type: select
    value: "sqlite"
    description: "Database dialect"
    section: "Database"
    options:
      - { value: "sqlite", label: "SQLite" }
      - { value: "mysql", label: "MySQL" }
      - { value: "postgresql", label: "PostgreSQL" }
    order: 1
  storage:
    type: string
    value: "/var/lib/zoneweaver/database/zoneweaver.db"
    description: "SQLite database file path"
    section: "Database"
    conditional:
      field: "database.dialect"
      value: "sqlite"
    order: 2
  host:
    type: host
    value: "localhost"
    description: "Database server hostname"
    section: "Database"
    conditional:
      field: "database.dialect"
      value: ["mysql", "postgresql"]
    order: 3
  port:
    type: integer
    value: 3306
    description: "Database server port"
    section: "Database"
    conditional:
      field: "database.dialect"
      value: ["mysql", "postgresql"]
    validation:
      min: 1
      max: 65535
    order: 4
  user:
    type: string
    value: ""
    description: "Database username"
    section: "Database"
    conditional:
      field: "database.dialect"
      value: ["mysql", "postgresql"]
    order: 5
  password:
    type: password
    value: ""
    description: "Database password"
    section: "Database"
    conditional:
      field: "database.dialect"
      value: ["mysql", "postgresql"]
    order: 6
  database_name:
    type: string
    value: "zoneweaver"
    description: "Database name"
    section: "Database"
    conditional:
      field: "database.dialect"
      value: ["mysql", "postgresql"]
    order: 7
  logging:
    type: boolean
    value: false
    description: "Enable database query logging"
    section: "Database"
    order: 8
  pool:
    max:
      type: integer
      value: 5
      description: "Maximum database connections"
      section: "Database"
      validation:
        min: 1
        max: 50
      order: 9
    min:
      type: integer
      value: 0
      description: "Minimum database connections"
      section: "Database"
      validation:
        min: 0
        max: 10
      order: 10
    acquire:
      type: integer
      value: 30000
      description: "Connection acquisition timeout (ms)"
      section: "Database"
      validation:
        min: 1000
        max: 60000
      order: 11
    idle:
      type: integer
      value: 10000
      description: "Connection idle timeout (ms)"
      section: "Database"
      validation:
        min: 1000
        max: 60000
      order: 12

# Session configuration (kept as-is for compatibility)
session:
  table: "sessions"
  secret: "${SESSION_SECRET:-${JWT_SECRET}}"

gravatar:
  api_key:
    type: string
    value: "4503:gk-kSPgIiM6imj2DOVlD3XV5uiXyXiF3klzQY5FQ2V3bDBohluexKlX2CR9OAPt_"
    description: "Gravatar API key for profile images"
    section: "Integrations"
    order: 1
