import { useState, useEffect } from "react";

import { useServers } from "../../contexts/ServerContext";
import { FormModal } from "../common";

const VlanCreateModal = ({ server, onClose, onSuccess, onError }) => {
  const [formData, setFormData] = useState({
    vid: "",
    link: "",
    name: "",
    force: false,
    temporary: false,
  });
  const [creating, setCreating] = useState(false);
  const [availableLinks, setAvailableLinks] = useState([]);
  const [loadingLinks, setLoadingLinks] = useState(false);

  const { makeZoneweaverAPIRequest } = useServers();

  // Load available links when modal opens
  useEffect(() => {
    loadAvailableLinks();
  }, [server]);

  // Auto-generate VLAN name when VID or link changes
  useEffect(() => {
    if (formData.vid && formData.link) {
      generateVlanName();
    }
  }, [formData.vid, formData.link]);

  const generateVlanName = async () => {
    if (!formData.vid || !formData.link) {
      return;
    }

    try {
      // Parse interface name to extract base name and PPA using dladm convention
      // Format: <name><PPA> where name is alphabetic, PPA is numeric
      const match = formData.link.match(/^([a-zA-Z]+)(\d+)$/);

      if (!match) {
        console.warn("Could not parse interface name:", formData.link);
        // Clear the name field so user can enter manually
        setFormData((prev) => ({
          ...prev,
          name: "",
        }));
        return;
      }

      const baseName = match[1]; // e.g., "igb"
      const ppa = parseInt(match[2]); // e.g., 0
      const vid = parseInt(formData.vid);

      // Apply dladm formula: <name><1000 * vid + PPA>
      // Example: igb0 + VID 999 = igb + (1000 * 999 + 0) = igb999000
      const autoGeneratedName = baseName + (1000 * vid + ppa);

      console.log("VLAN Auto-naming:", {
        input_link: formData.link,
        parsed_name: baseName,
        parsed_ppa: ppa,
        vid,
        calculation: `${baseName} + (1000 * ${vid} + ${ppa})`,
        result: autoGeneratedName,
      });

      // Check if auto-generated name conflicts with existing VLANs
      const vlansResult = await makeZoneweaverAPIRequest(
        server.hostname,
        server.port,
        server.protocol,
        "network/vlans",
        "GET"
      );

      const existingVlans = vlansResult.success
        ? vlansResult.data?.vlans || []
        : [];
      const existingNames = new Set(
        existingVlans.map((vlan) => vlan.link).filter(Boolean)
      );

      if (existingNames.has(autoGeneratedName)) {
        // If auto-generated name conflicts, clear the field so user enters manually
        console.warn("Auto-generated VLAN name conflicts:", autoGeneratedName);
        setFormData((prev) => ({
          ...prev,
          name: "",
        }));
      } else {
        // Use the correctly calculated auto-generated name
        setFormData((prev) => ({
          ...prev,
          name: autoGeneratedName,
        }));
      }
    } catch (err) {
      console.error("Error generating VLAN name:", err);
      // Clear name field on error so user can enter manually
      setFormData((prev) => ({
        ...prev,
        name: "",
      }));
    }
  };

  const loadAvailableLinks = async () => {
    if (!server || !makeZoneweaverAPIRequest) {
      return;
    }

    try {
      setLoadingLinks(true);

      // Load physical links that VLANs can be created on
      const linksResult = await makeZoneweaverAPIRequest(
        server.hostname,
        server.port,
        server.protocol,
        "monitoring/network/interfaces",
        "GET"
      );

      console.log("VLAN Link Loading Debug:", {
        linksResult: linksResult.success ? linksResult.data : linksResult,
      });

      const availableOptions = [];

      // Add physical links from monitoring/network/interfaces
      if (linksResult.success && linksResult.data?.interfaces) {
        linksResult.data.interfaces.forEach((link) => {
          // Only include physical interfaces for VLAN creation
          if (link.class === "phys" && link.link) {
            availableOptions.push({
              name: link.link,
              type: "Physical",
              state: link.state || "unknown",
              speed: link.speed || "unknown",
            });
          }
        });
      }

      // Deduplicate by name and filter out empty names
      const uniqueOptions = availableOptions
        .filter((option) => option.name && option.name.trim())
        .filter(
          (option, index, self) =>
            index === self.findIndex((o) => o.name === option.name)
        );

      console.log("VLAN Available Links:", uniqueOptions);
      setAvailableLinks(uniqueOptions);
    } catch (err) {
      console.error("Error loading available links:", err);
    } finally {
      setLoadingLinks(false);
    }
  };

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const validateForm = () => {
    if (!formData.vid) {
      onError("VLAN ID is required");
      return false;
    }

    const vlanId = parseInt(formData.vid);
    if (isNaN(vlanId) || vlanId < 1 || vlanId > 4094) {
      onError("VLAN ID must be between 1 and 4094");
      return false;
    }

    if (!formData.link.trim()) {
      onError("Physical link is required");
      return false;
    }

    // Validate VLAN name format if provided
    if (formData.name) {
      const nameRegex = /^[a-zA-Z][a-zA-Z0-9_]*$/;
      if (!nameRegex.test(formData.name)) {
        onError(
          "VLAN name must start with a letter and contain only letters, numbers, and underscores"
        );
        return false;
      }
    }

    return true;
  };

  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }

    try {
      setCreating(true);
      onError("");

      const requestData = {
        vid: parseInt(formData.vid),
        link: formData.link.trim(),
        force: formData.force,
        temporary: formData.temporary,
        created_by: "api",
      };

      // Calculate what the auto-generated name should be
      const match = formData.link.match(/^([a-zA-Z]+)(\d+)$/);
      const autoGeneratedName = match
        ? match[1] + (1000 * parseInt(formData.vid) + parseInt(match[2]))
        : "";
      const isCustomName =
        formData.name.trim() && formData.name.trim() !== autoGeneratedName;

      // Only send name if it's a custom name (different from auto-generated)
      // Let backend/dladm auto-generate if name matches the dladm formula or is empty
      if (isCustomName) {
        requestData.name = formData.name.trim();
      }

      console.log("VLAN Creation Request:", {
        requestData,
        isCustomName,
        autoGeneratedName,
        userProvidedName: formData.name.trim(),
        willSendName: isCustomName,
      });

      const result = await makeZoneweaverAPIRequest(
        server.hostname,
        server.port,
        server.protocol,
        "network/vlans",
        "POST",
        requestData
      );

      if (result.success) {
        onSuccess();
      } else {
        onError(result.message || "Failed to create VLAN");
      }
    } catch (err) {
      onError(`Error creating VLAN: ${err.message}`);
    } finally {
      setCreating(false);
    }
  };

  return (
    <FormModal
      isOpen
      onClose={onClose}
      onSubmit={handleSubmit}
      title="Create VLAN"
      icon="fas fa-tags"
      submitText="Create VLAN"
      submitVariant="is-primary"
      loading={creating}
    >
      <div className="columns">
        <div className="column">
          <div className="field">
            <label className="label">VLAN ID *</label>
            <div className="control">
              <input
                className="input"
                type="number"
                min="1"
                max="4094"
                placeholder="e.g., 100"
                value={formData.vid}
                onChange={(e) => handleInputChange("vid", e.target.value)}
                disabled={creating}
                required
              />
            </div>
            <p className="help">Valid range: 1-4094</p>
          </div>
        </div>
        <div className="column">
          <div className="field">
            <label className="label">Physical Link *</label>
            <div className="control">
              <div className="select is-fullwidth">
                <select
                  value={formData.link}
                  onChange={(e) => handleInputChange("link", e.target.value)}
                  disabled={creating || loadingLinks}
                  required
                >
                  <option value="">
                    {loadingLinks
                      ? "Loading available links..."
                      : "Select physical interface"}
                  </option>
                  {availableLinks.map((link, index) => (
                    <option key={index} value={link.name}>
                      {link.name} ({link.state}, {link.speed})
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="field">
        <label className="label">VLAN Name (Optional)</label>
        <div className="control">
          <input
            className="input"
            type="text"
            placeholder="Auto-generated using dladm formula"
            value={formData.name}
            onChange={(e) => handleInputChange("name", e.target.value)}
            disabled={creating}
          />
        </div>
        <p className="help">
          Shows auto-generated name preview. Leave empty or use the generated
          name to let dladm auto-generate.
        </p>
      </div>

      <div className="field">
        <div className="control">
          <label className="checkbox">
            <input
              type="checkbox"
              checked={formData.force}
              onChange={(e) => handleInputChange("force", e.target.checked)}
              disabled={creating}
            />
            <span className="ml-2">
              Force creation (override compatibility checks)
            </span>
          </label>
        </div>
        <p className="help is-size-7">
          Use with caution - forces VLAN creation even on incompatible devices
        </p>
      </div>

      <div className="field">
        <div className="control">
          <label className="checkbox">
            <input
              type="checkbox"
              checked={formData.temporary}
              onChange={(e) => handleInputChange("temporary", e.target.checked)}
              disabled={creating}
            />
            <span className="ml-2">
              Temporary (not persistent across reboots)
            </span>
          </label>
        </div>
      </div>
    </FormModal>
  );
};

export default VlanCreateModal;
