# Zoneweaver Production Configuration
# This file is installed to /etc/zoneweaver/config.yaml

app:
  name: Zoneweaver
  version: 0.0.1
  frontend_url: https://localhost:3443

mail:
  # Configure SMTP settings for email notifications
  smtp_connect:
    host: localhost
    port: 587
    secure: false
  smtp_auth:
    user: ""
    password: ""
  smtp_settings:
    from: Zoneweaver <noreply@localhost>

server:
  hostname: localhost
  port: 3443
  ssl:
    enabled: true
    generate_ssl: true  # Only applies if existing keys do not exist
    key: /etc/zoneweaver/ssl/key.pem
    cert: /etc/zoneweaver/ssl/cert.pem

frontend:
  port: 3443
  autoRefreshInterval: 5
  enableNotifications: true
  enableDarkMode: true

cors:
  whitelist:
    - https://localhost:3443
    - https://localhost
  options:
    origin: true
    preflightContinue: true
    credentials: true

backend_servers: []

environment:
  trust_proxy: 1

logging:
  level: info
  enabled: true

limits:
  maxServersPerUser: 10

security:
  jwt_secret: "__JWT_SECRET_FROM_FILE__"
  bcrypt_rounds: 10
  sessionTimeout: 24
  allow_new_organizations: true

database:
  path: /var/lib/zoneweaver/database/zoneweaver.db

session:
  store: 
    type: "sqlite"  # Default: "sqlite" | Alternative: "mysql"
    sqlite:
      path: "/var/lib/zoneweaver/database/sessions.db"
    mysql:
      host: "localhost"
      port: 3306
      user: "zoneweaver"
      password: ""
      database: "zoneweaver_sessions"

gravatar:
  # Get your API key from https://gravatar.com/
  apiKey: ""
